### ISSUE TITLE
json schema validation and autocomplete not working for non default helm value files

### ISSUE THREAD

**Issue by paologentili** [fstaudt/helm-values#105]
When using non default values files like `values-dev.yaml` there is no schema validation or autocomplete functionality.
Would be great to be able to activate the plugin functionalities for custom file patterns.

**Comment by fstaudt** [comment]
Hello @paologentili ,

JSON schema provider is currently provided for 2 patterns:
- `<chart_root_dir>/values.yaml`: [aggregation for chart](https://github.com/fstaudt/helm-values#aggregated-values-schemajson)
- `<chart_root_dir>/*-values.yaml`: [aggregation for packaged chart](https://github.com/fstaudt/helm-values#extra-values-schemajson)

I'm considering removing the second pattern (`*-values.yaml`) because it is too much linked to naming conventions in my company.\
The JSON schema for packaged chart would however still be generated even if it is not applied on any file by default.

In IntelliJ, JSON schema mappings provide the ability to select any JSON schema to validate a JSON / YAML file.\
In bottom-left corner, you just need to click on "No JSON schema" to display a list of available JSON schemas.
JSON schemas generated by helm-values plugin are shown in that list.\

![image](https://github.com/fstaudt/helm-values/assets/30255959/e03098b4-b7cf-4fbc-914e-ab0bd89da971)

Once JSON schema is selected for the file, configuration is persisted for your project.\
Auto-completion and validation of values is then available in the file.

JSON schema mappings can be modified in project settings.

I'm considering this IntelliJ feature as sufficient to support non-default values files.\
I don't plan to add custom file patterns in plugin configuration..

**Comment by paologentili** [comment]
thanks. using the json schema mapping is good enough for my use case
