### ISSUE TITLE
helm-values idea plugin deadlock on IntelliJ IDEA 2022.3.2 

### ISSUE THREAD

**Issue by gsaukov** [fstaudt/helm-values#64]
Hi!

Intellij IDEA constantly hangs (i suspect during index scan) after some time of usage of a large project. Disabling the plugin solves the issue.
It seems like it was not reproducible with previous IDEA 2021.
[threadDump-20230221-115555.txt](https://github.com/fstaudt/helm-values/files/10793838/threadDump-20230221-115555.txt)

Intellij IDEA Build #IU-223.8617.56, built on January 26, 2023
Runtime version: 17.0.5+1-b653.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Apple M1 Max Mac OS Ventura 13.1

**Comment by gsaukov** [comment]
Perhaps this happens due to symlink ref.
Based on info from Mostafa Nagib from IDEA plugin review page.

**Comment by fstaudt** [comment]
Hello @gsaukov 

thanks for reporting the issue, I'll look into it.

Do you have an example of large project (preferably open source) where the issue can be reproduced ?

Could you also provide more info on usage of symlink refs in helm charts?
Feedback provided in plugin review page was unclear.

Thx in advance !

**Comment by fstaudt** [comment]
@gsaukov ,

I've made some performance improvements on JsonSchema providers with release 0.6.1.

Please let me know if latest version of the plugin has improved the situation on your side.\
If there is any information that you can share about your project that could help me track the issue, please let me know.

**Comment by gsaukov** [comment]
@fstaudt 
Hi, it is still 0.6.0 in Idea's market place.

**Comment by fstaudt** [comment]
@gsaukov

release 0.6.1 was done yesterday in github.

It takes a few days to be available for update.

**Comment by gsaukov** [comment]
Hi @fstaudt 

Same thing 0.6.1, it crashes almost immediately on idea start.

The project that crashes is SAP commerce, it is very large JAVA monolith.
You may find IDEA log and thread dump in the attachment. However it is possible that my Idea configuration or some other conditions are very unique. But when I disable helm-values plugin, it does not crash at all.

[IDEALOG_AND_THREAD_DUMP.txt](https://github.com/fstaudt/helm-values/files/11162017/IDEALOG_AND_THREAD_DUMP.txt)

**Comment by fstaudt** [comment]
Hello @gsaukov ,

does your project contain any Helm chart ?

Performance improvements in 0.6.1 were focused on background tasks performed by the plugin when IDE is already running.\
I had the understanding that issues on your project only happened after some time of usage.

A crash at startup can only be caused by JSON schema provider factory in helm-values plugin.\
The factory searches the complete repository to find directories containing a file named `Chart.yaml`.\
For large projects containing a lot of files and subdirectories, I imagine it can take a lot of time.\
Inspection at startup could be limited to the first level of directories to improve performance and possibly avoid a crash.

I can create a SNAPSHOT version of the plugin with a fix that you can test on your project.\
Would you be OK to test a SNAPSHOT version of the plugin on your project ?
